static:
  command: npm run start
  build: .
  ports:
    - "8090:3000"
  working_dir: /usr/src/app
  environment:
    VIRTUAL_HOST: static-gabriel.siedler.ninja
    VIRTUAL_PORT: 3000
    GITHUB_TOKEN: # should be specified in host's machine
    CODEWARS_TOKEN: # should be specified in host's machine
  volumes:
    - .:/usr/src/app
